"""Groq client using direct HTTPX for high-throughput Llama 3.3 and DeepSeek inference.

Provides fast fallback and alternative LLM execution without external SDK dependencies.
"""

from __future__ import annotations

import logging
from typing import Any

import httpx

from app.core.config import settings

logger = logging.getLogger(__name__)

GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions"

# Primary high-reasoning models on Groq
GROQ_MODELS = [
    "llama-3.3-70b-versatile",
    "deepseek-r1-distill-llama-70b",
    "llama-3.1-8b-instant",
]


def is_groq_configured() -> bool:
    """Check whether a Groq API key is present."""
    return bool(settings.groq_api_key and settings.groq_api_key.strip())


def invoke_groq(
    prompt: str,
    model: str | None = None,
    temperature: float = 0.2,
    timeout: float = 60.0,
) -> str:
    """Invoke Groq's OpenAI-compatible API with Llama 3.3 / DeepSeek models.

    Args:
        prompt: The user instruction / text prompt.
        model: Model code (defaults to settings.groq_model or 'llama-3.3-70b-versatile').
        temperature: Sampling temperature.
        timeout: HTTP timeout in seconds.

    Returns:
        The text response generated by the model.

    Raises:
        RuntimeError: If Groq API key is missing or all Groq models fail.
    """
    api_key = settings.groq_api_key.strip() if settings.groq_api_key else ""
    if not api_key:
        raise RuntimeError("GROQ_API_KEY is not configured in backend/.env")

    target_models = [model] if model else [settings.groq_model, *GROQ_MODELS]
    # Deduplicate while preserving order
    seen = set()
    candidate_models = []
    for m in target_models:
        if m and m not in seen:
            seen.add(m)
            candidate_models.append(m)

    headers = {
        "Authorization": f"Bearer {api_key}",
        "Content-Type": "application/json",
    }

    last_error = None
    for candidate in candidate_models:
        payload: dict[str, Any] = {
            "model": candidate,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "You are an expert grant proposal and non-profit strategy consultant "
                        "specializing in Indian CSR, Ministry grants, and statutory filings."
                    ),
                },
                {"role": "user", "content": prompt},
            ],
            "temperature": temperature,
            "max_tokens": 4096,
        }

        try:
            with httpx.Client(timeout=timeout) as client:
                response = client.post(GROQ_API_URL, headers=headers, json=payload)

            if response.status_code == 200:
                data = response.json()
                choices = data.get("choices", [])
                if choices and "message" in choices[0]:
                    content = choices[0]["message"].get("content", "")
                    logger.info("Groq invocation succeeded with model '%s' (%d chars)", candidate, len(content))
                    return str(content)
                raise ValueError(f"Unexpected response structure from Groq: {data}")

            # Rate limit or quota error on Groq
            logger.warning(
                "Groq model '%s' failed with status %d: %s",
                candidate,
                response.status_code,
                response.text[:200],
            )
            last_error = RuntimeError(f"Groq API error ({response.status_code}): {response.text[:300]}")

        except Exception as e:
            logger.warning("Error invoking Groq model '%s': %s", candidate, e)
            last_error = e
            continue

    if last_error:
        raise last_error
    raise RuntimeError("All candidate Groq models failed")
